- repo: local
  hooks:
  - id: salt-lint
    name: salt-lint
    entry: salt-lint --no-check-line-length -f
    language: system
    files: \.sls$
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: 5da199bb8d60f764c0f77a20b0a1dc3a7640bcdd
  hooks:
  - id: trailing-whitespace
    files: \.(js|rb|md|py|sh|txt|yaml|yml|sls|conf)$
  - id: check-yaml
  - id: end-of-file-fixer
    files: \.(asciidoc|adoc|conf|coffee|cpp|css|c|ejs|erb|groovy|h|haml|hh|hpp|hxx|html|in|j2|jade|json|js|less|markdown|md|ml|mli|pp|py|rb|rs|R|scala|scss|sh|slim|sls|tex|tmpl|ts|txt|yaml|yml)$
  - id: trailing-whitespace
    files: \.(asciidoc|adoc|conf|coffee|cpp|css|c|ejs|erb|groovy|h|haml|hh|hpp|hxx|html|in|j2|jade|json|js|less|markdown|md|ml|mli|pp|py|rb|rs|R|scala|scss|sh|slim|sls|tex|tmpl|ts|txt|yaml|yml)$
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-symlinks
  - id: detect-private-key
- repo: git://github.com/detailyang/pre-commit-shell
  sha: 1fdffa0434cde2b87f19ad258201d3e81481af5f
  hooks:
  - id: shell-lint
    args:
    - --shell=bash
